[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    blynkkk/Blynk @ ^1.3.2
    mikalhart/TinyGPSPlus @ ^1.0.3
    adafruit/Adafruit INA219 @ ^1.2.3

build_flags =
    -D BLYNK_PRINT=Serial
    -D PROJECT_NAME=\"Line Fault Detection System\"
